name: 'supabase_gas'
description: 'A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.'
version: '2.6.3'
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
documentation: 'https://supabase.com/docs/reference/dart/introduction'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  google_apps_script_library: '^0.0.10'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: true
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  general_universe:
    path: '../../../../../galaxeus/app/general_developer_public_library_project/packages/general_universe'
  google_apps_script_library:
    path: '../google_apps_script_library'
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
  server_universe:
    path: '../../../../../galaxeus/app/general_developer_public_library_project/packages/server_universe'
funding: []
