name: 'gotrue'
description: 'A dart client library for the GoTrue API.'
version: '2.11.1'
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/gotrue'
documentation: 'https://supabase.com/docs/reference/dart/auth-signup'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '^1.19.0'
  crypto: '^3.0.2'
  http: '^1.3.0'
  jwt_decode: '^0.3.1'
  logging: '^1.2.0'
  meta: '^1.16.0'
  retry: '^3.1.0'
  rxdart: '>=0.27.7 <0.29.0'
dev_dependencies:
  dart_jsonwebtoken: '^2.4.1'
  dotenv: '^4.1.0'
  lints: '^5.0.0'
  otp: '^3.1.3'
  test: 'any'
false_secrets:
  - '/infra/docker-compose.yml'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
funding: []
