name: 'postgrest'
description: 'PostgREST client for Dart. This library provides an ORM interface to PostgREST.'
version: '2.4.1'
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/postgrest'
documentation: 'https://supabase.com/docs/reference/dart/select'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  http: '^1.3.0'
  logging: '^1.2.0'
  meta: '^1.16.0'
  yet_another_json_isolate: '2.0.3'
dev_dependencies:
  collection: '^1.19.0'
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
funding: []
