name: 'telegram_gas'
description: 'A sample command-line application.'
version: '1.0.0'
publish_to: 'none'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  google_apps_script_library:
    path: '../google_apps_script_library'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
  is_use_direct_package: true
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  general_universe:
    path: '../../../../../galaxeus/app/general_developer_public_library_project/packages/general_universe'
  mime: '^2.0.0'
  pointycastle: '^4.0.0' 
funding: []
