name: 'google_apps_script_library'
description: 'GGML Is Library machine learning in dart with special feature speed up inference model in cpu only or any gpu'
version: '0.0.10'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/google_apps_script_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'general'
  - 'bot'
  - 'userbot'
executables:
  google_apps_script_library: 'bin/google_apps_script_library.dart'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  collection: '^1.19.0'
  ffi: '^2.1.4'
  general_universe: '^0.0.0'
  http: '^1.3.0'
  mime: '^2.0.0'
  path: '^1.9.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  general_universe:
    path: '../../../../../galaxeus/app/general_developer_public_library_project/packages/general_universe'
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
flutter:
  uses-material-design: true
project:
  type: ''
  is_use_direct_package: true
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
